### ISSUE TITLE
inconsistent link colors

### ISSUE THREAD

**Issue by castedo** [tskit-dev/tskit-site#132] opened 2022-10-18 01:49 UTC
For the first half of https://tskit.dev/genetics-research/ the hyperlinks are white. Then in the later half they are aqua.

On https://tskit.dev/software/ they are white and then for "website GitHub repository" hyperlink it is blue.

Most of the rest of the site seems to have consistent aqua color hyperlinks.

**Comment by jeromekelleher** [comment] 2022-11-02 13:46
Dupe of #122

**Closed by jeromekelleher** 2022-11-02 13:46 UTC
